services:
  flame:
    image: pawelmalak/flame:2.2.2 # next use 2.3.0
    container_name: flame
    volumes:
      - /path/to/host/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    secrets:
      - password
    environment:
      - PASSWORD=flame_password
      - PASSWORD_FILE=/run/secrets/password
    restart: unless-stopped

secrets:
  password:
    file: WEBPASSWORD_FILE.txt
